### ISSUE TITLE
Determination Of Cars VS Pedestrians: Implementation

### ISSUE THREAD

**Issue by LandonCasey** [haganwalker/glowbridge#2]
I wanted to know some thoughts before I completely bash out these functions.

Do we want to send distance data from the slave device to the master device, or would we rather want to send a code from the slave device to the master based on a threshold:

- "A" for pedestrian crossing
- "Z" for vehicle crossing

Or something along those lines.

I tend to lean more towards the code so we're only communicating when we need to be.

**Comment by haganwalker** [comment]
I agree. Less comms is better, so only send from slave if we've verified person or vehicle - especially if we go with 433mhz since it's a somewhat restricted band (you can send several times an hour, but if we can only send data when needed, I think that's preferred).

**Comment by LandonCasey** [comment]
Updated in the newest commit to my branch.
Added a function to the slave code that takes in ultrasonic values and pushes out pedestrian or car codes automagically
